### PR TITLE
Minor typo correction

### PR DESCRIPTION
**Pull request by avilaton**
Bumped into this while swaping 0.2.0 for 0.3.0. 
Great job by the way!

### CODE REVIEW

**Comment by mattupstate** [comment]
Can you squash this into one commit?

**Comment by avilaton** [comment]
Done, I just found the other typo after submiting the PR. A test would have caught this second one.

**Comment by arcivanov** [comment]
Can you escalate merging this please?

**Comment by arcivanov** [comment]
Thanks so much!

**Comment by mattupstate** [comment]
I'm releasing this, but I'd like to mention that this handler option is going to be deprecated as I don't see any real value in being able to override the entire auth resource view function. This should be done be disabling the auth resource by setting `JWT_AUTH_URL_RULE = None` and registering your own auth handler.

**Pull request merged**
