### PR TITLE
do not server error on non-json auth attempt

### PR DESCRIPTION
**Pull request by peterlada**
Fix for issue #58

request.get_json() returns None if request content type is not application/json, it is not handled more gracefully than a 500 Server Error.

### CODE REVIEW

**Comment by dequis** [comment]
Heh, I was about to PR the same thing. @mattupstate this is a straightforward merge IMO.

**Comment by alexmensch** [comment]
Any chance we could merge this one? 😄

**Comment by sreejeet** [comment]
Looks like a simple merge, why is this one still not merged? Is there more to be done here? I could contribute if required.

**Comment by peterlada** [comment]
Seems like most people use PyJWT nowadays, closing this abandoned PR.

**Pull request closed without merging**
